version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - egurinko
  assignees:
  - egurinko
  ignore:
  - dependency-name: twilio
    versions:
    - 3.55.1
