version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cypress/base:12.6.0
        environment:
          TERM: xterm

      - image: circleci/postgres:latest-postgis
        environment:
          POSTGRES_USER: toru
          POSTGRES_DB: kudos_app

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Install sudo for cypress/base because it's debian
      - run:
          name: Install sudo
          command: apt-get update && apt-get install -y sudo

      # Install dockerize to wait for mongodb start
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Wait for Postgres to start
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: database setup
          command: |
            yarn migrate
            yarn seed

      - run:
          name: build app
          command: CI=false && yarn build

      - run:
          name: start server
          command: yarn start
          background: true

      # run cypress test!
      - run:
          name: run cypress tests
          command: |
            yarn test:wait
